[platformio]
default_envs = pd_stepper

[env]
lib_ldf_mode = deep+

[env:pd_stepper]
platform = espressif32@6.11.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_mode = dio
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=1
lib_deps =
    gin66/FastAccelStepper@0.34.0
    teemuatlut/TMCStepper@0.7.3
    ESP32Async/AsyncTCP@3.4.10
    ESP32Async/ESPAsyncWebServer@3.9.6
    bblanchon/ArduinoJson@7.4.3

[env:native]
platform = native
test_framework = unity
test_build_src = no
lib_compat_mode = off
